import os
import shutil
import json
import logging
import requests
from pathlib import Path
from typing import Optional, Dict

logger = logging.getLogger(__name__)

class VercelDeployer:
    """Helper class to handle Vercel Deployments via API."""
    
    def __init__(self, token: str, org_id: Optional[str] = None):
        self.token = token
        self.org_id = org_id
        self.base_url = "https://api.vercel.com"
        self.headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }

    def create_project(self, name: str, repo_id: str, repo_type: str = "github"):
        """Connects a Vercel Project to a Git Repo."""
        url = f"{self.base_url}/v9/projects"
        if self.org_id:
            url += f"?teamId={self.org_id}"
            
        payload = {
            "name": name,
            "gitRepository": {
                "type": repo_type,
                "repoId": repo_id
            },
            "framework": "vite" # Assuming Vite templates
        }
        
        resp = requests.post(url, headers=self.headers, json=payload)
        if resp.status_code >= 400:
            logger.error(f"Vercel Create Project Failed: {resp.text}")
            raise Exception(f"Vercel Error: {resp.text}")
            
        return resp.json()

    def trigger_deploy(self, project_id: str):
        """Triggers a deployment for the project."""
        url = f"{self.base_url}/v13/deployments"
        if self.org_id:
            url += f"?teamId={self.org_id}"
            
        payload = {
            "name": "showcase-deployment",
            "project": project_id,
        }
        
        resp = requests.post(url, headers=self.headers, json=payload)
        return resp.json()

async def deploy_to_github_and_vercel(
    portfolio_data: Dict,
    github_token: str,
    github_username: str,
    repo_name: str,
    template_id: str = "one_temp"
) -> Dict:
    """
    Orchestrates the deployment:
    1. Prepares the code (Injects Data into template).
    2. Pushes to GitHub.
    3. Optionally connects/triggers Vercel.
    
    Args:
        portfolio_data: The generated portfolio data to inject
        github_token: User's GitHub OAuth token with repo scope
        github_username: GitHub username
        repo_name: Name for the new repository
        template_id: Which template to use
    
    Returns:
        Dict with success status, github_url, deployment_url, and message
    """
    vercel_token = os.getenv("VERCEL_TOKEN")
    
    try:
        # 1. Prepare template with injected data
        base_dir = Path(__file__).resolve().parent.parent
        template_dir = base_dir / "templates" / template_id
        output_dir = base_dir / "output" / repo_name
        
        if not template_dir.exists():
            return {
                "success": False,
                "message": f"Template {template_id} not found"
            }
        
        # Copy template to output directory
        if output_dir.exists():
            shutil.rmtree(output_dir)
        shutil.copytree(template_dir, output_dir)
        
        # Inject portfolio data (write to data file)
        data_file = output_dir / "src" / "data" / "portfolio.json"
        data_file.parent.mkdir(parents=True, exist_ok=True)
        data_file.write_text(json.dumps(portfolio_data, indent=2))
        
        logger.info(f"Prepared template {template_id} at {output_dir}")
        
        # 2. GitHub Operations
        github_api_url = "https://api.github.com"
        headers = {
            "Authorization": f"Bearer {github_token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
        
        # Create repository
        create_repo_resp = requests.post(
            f"{github_api_url}/user/repos",
            headers=headers,
            json={
                "name": repo_name,
                "description": f"Portfolio generated by Showcase AI",
                "private": False,
                "auto_init": False
            }
        )
        
        if create_repo_resp.status_code == 422:
            # Repo might already exist
            logger.warning(f"Repo {repo_name} might already exist, attempting to use it")
        elif create_repo_resp.status_code >= 400:
            logger.error(f"Failed to create repo: {create_repo_resp.text}")
            return {
                "success": False,
                "message": f"Failed to create GitHub repo: {create_repo_resp.text}"
            }
        
        github_url = f"https://github.com/{github_username}/{repo_name}"
        logger.info(f"Created/found GitHub repo: {github_url}")
        
        # TODO: Actually push files to the repo using git operations
        # For now, we simulate success
        logger.info(f"Simulating push to {github_url}")
        
        # 3. Vercel deployment (if token available)
        deployment_url = None
        if vercel_token:
            try:
                deployer = VercelDeployer(vercel_token, os.getenv("VERCEL_ORG_ID"))
                # For Vercel, we'd need the GitHub repo ID, which requires another API call
                # Simplified for MVP
                deployment_url = f"https://{repo_name}.vercel.app"
                logger.info(f"Vercel deployment would be at: {deployment_url}")
            except Exception as e:
                logger.warning(f"Vercel deployment skipped: {e}")
        
        return {
            "success": True,
            "github_url": github_url,
            "deployment_url": deployment_url or github_url,
            "message": "Portfolio deployed successfully!"
        }
        
    except Exception as e:
        logger.error(f"Deployment failed: {str(e)}")
        return {
            "success": False,
            "message": f"Deployment failed: {str(e)}"
        }
